#!/usr/bin/env python
"""
Simple example that parametrizes a 2d joint-space path.
"""
from matplotlib import pyplot as plt
import numpy as np

import traj

# Joint limits (assumed to be the same for all axes).
max_velocities = np.array([0.3, 0.3])
max_accelerations = np.array([1.0, 1.0])
max_jerks = np.array([10.0, 10.0])

# Test path
path = np.array([(0.0, 0.0), (0.5, 0.6), (1.5, 0.8), (-0.2, 0.4)])

(trajectory_position_function, trajectory_velocity_function, trajectory_acceleration_funciton,
 trajectory_jerk_function) = traj.trajectory_for_path(path, max_velocities, max_accelerations, max_jerks)

traj.plot.plot_trajectory(plt.figure(), trajectory_position_function, trajectory_velocity_function,
                          trajectory_acceleration_funciton, trajectory_jerk_function)

plt.figure()
traj.plot.plot_2d_path(plt.gca(), trajectory_position_function, 1000, label='trajectory points')
# Plot the waypoints in the original path for comparison.
plt.plot([q[0] for q in path], [q[1] for q in path], 'bx', label='original waypoints')

plt.show()
