#!/usr/bin/env python
"""
Simple example that parametrizes a 2d joint-space path.
"""
import argparse

from matplotlib import pyplot as plt
import matplotlib.patches
import matplotlib.collections
import numpy as np
import traj

# Test path
path = np.array([(0.0, 0.0), (1.0, 1.0), (1.5, 0.8), (-0.2, 0.4)])

parser = argparse.ArgumentParser(description='Parameterize a geometric path.')
parser.add_argument('--blend-radius', default=0.2,
                    help='radius of blend arcs between segments (zero for no blending)')
args = parser.parse_args()

path_function = traj.parameterize_path(path)
if args.blend_radius > 0.0:
    path_function = traj.blend_parameterized_path(path_function, args.blend_radius)

# Plot sampled points along the parameterized path.
traj.plot.plot_2d_path(plt.gca(), path_function, 100)

# Plot the waypoints in the original path for comparison.
plt.plot([q[0] for q in path], [q[1] for q in path], 'bx', label='original waypoints')

# Plot the blend radii as circles around each waypoint.
blend_patches = matplotlib.collections.PatchCollection(
    [matplotlib.patches.Circle((q[0], q[1]), args.blend_radius) for q in path])
plt.gca().add_collection(blend_patches)

plt.gca().set_aspect('equal')

plt.legend()
plt.show()
