#!/usr/bin/env python
import argparse

from matplotlib import pyplot as plt
import numpy as np
import rosbag
import sys


def compute_discrete_derivatives(positions, itp=0.008):
    num_joints = positions.shape[1]
    velocities = [np.zeros((num_joints,))]
    accelerations = [np.zeros((num_joints,))]
    jerks = [np.zeros((num_joints,))]
    for point_i in range(1, len(positions)):
        velocities.append((positions[point_i] - positions[point_i - 1]) / itp)
        accelerations.append((velocities[point_i] - velocities[point_i - 1]) / itp)
        jerks.append((accelerations[point_i] - accelerations[point_i - 1]) / itp)
    return np.array(velocities), np.array(accelerations), np.array(jerks)


def plot_discrete_trajectory(axes, times, positions, velocities, accelerations, jerks, label, linewidth=1, color='b',
                             style='-',
                             marker=''):
    num_joints = positions.shape[1]
    axes[0, 0].set_ylabel('position')
    axes[1, 0].set_ylabel('velocity')
    axes[2, 0].set_ylabel('acceleration')
    axes[3, 0].set_ylabel('jerk')
    for joint_i in range(num_joints):
        c = joint_colors[joint_i]
        axes[0, joint_i].plot(times, positions[:, joint_i], style, c=color, marker=marker, linewidth=linewidth,
                              label=label)
        axes[1, joint_i].plot(times, velocities[:, joint_i], style, c=color, marker=marker, linewidth=linewidth,
                              label=label)
        axes[2, joint_i].plot(times, accelerations[:, joint_i], style, c=color, marker=marker, linewidth=linewidth,
                              label=label)
        axes[3, joint_i].plot(times, jerks[:, joint_i], style, c=color, marker=marker, linewidth=linewidth, label=label)
        axes[3, joint_i].set_xlabel('joint_{}'.format(joint_i + 1))


joint_colors = ['r', 'b', 'g', 'c', 'm', 'y', 'k', 'w']

parser = argparse.ArgumentParser()
parser.add_argument('bag', help='Path to bagfile')
parser.add_argument('--njoints', help='Number of joints', default=6, type=float)
parser.add_argument('--period', help='Control cycle period in seconds', default=0.008, type=float)
parser.add_argument('--goal-start', help='Start time of goal', default=0.0, type=float)
args = parser.parse_args()

goal_msg = None
command_times = []
command_positions = []
state_times = []
state_positions = []
bag = rosbag.Bag(args.bag)
for topic, msg, t in bag.read_messages():
    if msg._type == 'fanuc_j519_msgs/Command':
        command_times.append(msg.header.stamp.to_sec())
        command_positions.append(np.deg2rad(msg.axes_data[:args.njoints]))
    elif msg._type == 'control_msgs/FollowJointTrajectoryActionGoal':
        goal_msg = msg.goal
        goal_time = t.to_sec()
    elif msg._type == 'fanuc_j519_msgs/RobotState':
        state_times.append(msg.header.stamp.to_sec())
        state_positions.append(np.deg2rad(msg.joint_pose[:args.njoints]))

bag.close()

command_times = np.array(command_times)
command_positions = np.array(command_positions)
state_times = np.array(state_times)
state_positions = np.array(state_positions)
goal_times = (np.array(
    [p.time_from_start.to_sec() for p in goal_msg.trajectory.points]) + goal_time)
goal_positions = np.array([p.positions for p in goal_msg.trajectory.points])

# Subtracting off the start time so we have "time since beginning of data" instead of "time since 1970".
start_time = command_times[0]
command_times -= start_time
state_times -= start_time
goal_times -= start_time

# Add manual time offset to goal points to line it up with the controller data.
goal_times += args.goal_start


figure = plt.gcf()
figure.suptitle('Driver command and state')
axes = figure.subplots(4, args.njoints, squeeze=False, sharex=True, sharey='row')

goal_velocities, goal_accelerations, goal_jerks = compute_discrete_derivatives(goal_positions, args.period)
plot_discrete_trajectory(axes, goal_times, goal_positions, goal_velocities, goal_accelerations, goal_jerks,
                         'Goal', style='-',
                         color='0.75', linewidth=4)

command_velocities, command_accelerations, command_jerks = compute_discrete_derivatives(command_positions, args.period)
plot_discrete_trajectory(axes, command_times, command_positions, command_velocities, command_accelerations,
                         command_jerks, 'Command', style=':', color='0.0', linewidth=2)

state_velocities, state_accelerations, state_jerks = compute_discrete_derivatives(state_positions, args.period)
plot_discrete_trajectory(axes, state_times, state_positions, state_velocities, state_accelerations, state_jerks,
                         'State', style='--', color='0.0', linewidth=2)



figure.legend()
plt.show()
