#!/usr/bin/env python
"""
Simple example that computes a seven segment motion profile a 1d motion with given start and
end positions. Start and end velocity/acceleration/jerk are assumed to be zero.
"""
from matplotlib import pyplot as plt
import numpy as np

import traj

# j_max, a_max, v_max, p_start, p_end
tests = [
        (0.1, 3.0, 0.1, 0.0, 30.0), # Reach max velocity bot not max acceleration
        (0.1, 3.0, 6.0, 0.0, 30.0), # Reach max acceleration but not max velocity
        (0.1, 2.3, 3.1, 0.0, 0.4), # Don't reach max velocity or max acceleration
        (0.1, 0.4, 2.0, 0.0, 30.0), # Reach max acceleration and also velocity
        ]

# Test path
path = np.array([(0.0, 0.0), (1.0, 1.0), (1.5, 0.8), (-0.2, 0.4)])

path_function = traj.parameterize_path(path)

# Plot sampled points along the parametrized path.
traj.plot.plot_2d_path(path_function, 100)

# Plot the waypoints in the original path for comparison.
plt.plot([q[0] for q in path], [q[1] for q in path], 'bx', label='original waypoints')

plt.legend()
plt.show()

