#!/usr/bin/env python
"""
Simple example that computes a seven segment motion profile a 1d motion with given start and
end positions. Start and end velocity/acceleration/jerk are assumed to be zero.
"""
import time

from matplotlib import pyplot as plt
from sympy import Symbol

import traj

j_max = 10.0
a_max = 2.0
v_max = 10.0
p_start = 0.0
p_end = 30.0
v_start = 0.0
v_end = 1.5

t = Symbol('t')

t_start = time.time()
jerk = traj.seven_segment_type4.fit(p_start, p_end, v_start, v_end, v_max, a_max, j_max, t, 8)
print('Fit function in {} seconds'.format(time.time() - t_start))

t_start = time.time()
acceleration = jerk.integrate(0.0)
velocity = acceleration.integrate(v_start)
position = velocity.integrate(p_start)
print('Integrated function in {} seconds'.format(time.time() - t_start))

t_start = time.time()
traj.plot.plot_trajectory(plt.gcf(), position, velocity, acceleration, jerk, n_points=100,
                          v_max=v_max, a_max=a_max, j_max=j_max)

print('Plotted function in {} seconds'.format(time.time() - t_start))
plt.show()
